on:
  push:
    branches: master

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-16.04
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/xenial/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: release
          http-user-agent: R/4.1.0 (ubuntu-16.04) R (4.1.0 x86_64-pc-linux-gnu x86_64 linux-gnu) on GitHub Actions

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-tinytex@v1

      - name: install libgit2-dev
        if: runner.os == 'Linux'
        run: sudo add-apt-repository ppa:cran/libgit2 && sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main" && sudo apt-get update && sudo apt-get install libssh2-1-dev libgit2-dev libudunits2-dev  libgmp-dev libmpfr-dev libmpc-dev libharfbuzz-dev libfribidi-dev libicu-dev libicu55 libpng12-0 libcurl3-openssl-dev libgconf-2-4 -y
        shell: bash

      - name: Install packages from cran (source)
        run: |
          install.packages('remotes')
          remotes::install_github("jeroen/curl")
          remotes::install_github("nlmixrdevelopment/dparser-R")
          remotes::install_cran("stringi")
          remotes::install_github("https://github.com/symengine/symengine.R")
          remotes::install_cran("covr")
        shell: Rscript {0}

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          install.packages("remotes")
          # To get links for homepage
          remotes::install_cran("devtools")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("nlmixrdevelopment/dparser-R")
          remotes::install_github("jeroen/curl")
          remotes::install_dev("pkgdown")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
